// 제시어 은행
// 각 카테고리는 { word, spy } 쌍의 배열입니다.
//  - word: 시민들이 받는 제시어
//  - spy : 스파이 모드일 때 라이어가 받는 "비슷한" 단어
const WORD_BANK = {
  "음식": [
    { word: "김치", spy: "깍두기" },
    { word: "피자", spy: "햄버거" },
    { word: "치킨", spy: "닭강정" },
    { word: "라면", spy: "우동" },
    { word: "떡볶이", spy: "순대" },
    { word: "초밥", spy: "회" },
    { word: "삼겹살", spy: "목살" },
    { word: "아이스크림", spy: "빙수" },
    { word: "김밥", spy: "주먹밥" },
    { word: "짜장면", spy: "짬뽕" },
    { word: "커피", spy: "녹차" },
    { word: "케이크", spy: "빵" },
  ],
  "동물": [
    { word: "강아지", spy: "고양이" },
    { word: "사자", spy: "호랑이" },
    { word: "코끼리", spy: "코뿔소" },
    { word: "기린", spy: "사슴" },
    { word: "펭귄", spy: "오리" },
    { word: "독수리", spy: "매" },
    { word: "상어", spy: "고래" },
    { word: "토끼", spy: "다람쥐" },
    { word: "곰", spy: "판다" },
    { word: "원숭이", spy: "고릴라" },
    { word: "뱀", spy: "도마뱀" },
    { word: "말", spy: "당나귀" },
  ],
  "장소": [
    { word: "학교", spy: "학원" },
    { word: "병원", spy: "약국" },
    { word: "공항", spy: "기차역" },
    { word: "영화관", spy: "극장" },
    { word: "카페", spy: "식당" },
    { word: "바다", spy: "강" },
    { word: "산", spy: "언덕" },
    { word: "백화점", spy: "마트" },
    { word: "도서관", spy: "서점" },
    { word: "놀이공원", spy: "동물원" },
    { word: "공원", spy: "운동장" },
    { word: "호텔", spy: "펜션" },
  ],
  "직업": [
    { word: "의사", spy: "간호사" },
    { word: "선생님", spy: "교수" },
    { word: "경찰", spy: "군인" },
    { word: "요리사", spy: "제빵사" },
    { word: "가수", spy: "배우" },
    { word: "변호사", spy: "판사" },
    { word: "소방관", spy: "구급대원" },
    { word: "화가", spy: "디자이너" },
    { word: "농부", spy: "어부" },
    { word: "운동선수", spy: "코치" },
    { word: "프로그래머", spy: "해커" },
    { word: "파일럿", spy: "승무원" },
  ],
  "스포츠": [
    { word: "축구", spy: "풋살" },
    { word: "야구", spy: "소프트볼" },
    { word: "농구", spy: "핸드볼" },
    { word: "배구", spy: "족구" },
    { word: "테니스", spy: "배드민턴" },
    { word: "수영", spy: "다이빙" },
    { word: "골프", spy: "당구" },
    { word: "권투", spy: "태권도" },
    { word: "스키", spy: "스노보드" },
    { word: "마라톤", spy: "달리기" },
    { word: "탁구", spy: "스쿼시" },
    { word: "양궁", spy: "사격" },
  ],
  "사물": [
    { word: "휴대폰", spy: "태블릿" },
    { word: "노트북", spy: "컴퓨터" },
    { word: "시계", spy: "알람" },
    { word: "우산", spy: "양산" },
    { word: "안경", spy: "선글라스" },
    { word: "칫솔", spy: "치약" },
    { word: "냉장고", spy: "에어컨" },
    { word: "텔레비전", spy: "모니터" },
    { word: "의자", spy: "소파" },
    { word: "가방", spy: "지갑" },
    { word: "베개", spy: "이불" },
    { word: "연필", spy: "볼펜" },
  ],
};
