// 제시어 은행 (초3~중2 눈높이 / 자녀와 함께 즐기는 버전)
// 각 카테고리는 { word, spy } 쌍의 배열입니다.
//  - word: 시민들이 받는 제시어
//  - spy : 스파이 모드일 때 라이어가 받는 "비슷한" 단어
// 각 카테고리에 이모지를 붙여 귀엽게 표시합니다.
const WORD_BANK = {
  "🐶 동물": [
    { word: "강아지", spy: "고양이" },
    { word: "토끼", spy: "다람쥐" },
    { word: "사자", spy: "호랑이" },
    { word: "곰", spy: "판다" },
    { word: "코끼리", spy: "하마" },
    { word: "기린", spy: "사슴" },
    { word: "원숭이", spy: "고릴라" },
    { word: "펭귄", spy: "오리" },
    { word: "닭", spy: "병아리" },
    { word: "돼지", spy: "소" },
    { word: "말", spy: "얼룩말" },
    { word: "여우", spy: "늑대" },
    { word: "햄스터", spy: "다람쥐" },
    { word: "돌고래", spy: "고래" },
    { word: "상어", spy: "물고기" },
    { word: "거북이", spy: "달팽이" },
    { word: "개구리", spy: "두꺼비" },
    { word: "나비", spy: "잠자리" },
  ],
  "🍚 음식": [
    { word: "김밥", spy: "주먹밥" },
    { word: "라면", spy: "우동" },
    { word: "떡볶이", spy: "순대" },
    { word: "치킨", spy: "피자" },
    { word: "햄버거", spy: "핫도그" },
    { word: "짜장면", spy: "짬뽕" },
    { word: "김치", spy: "단무지" },
    { word: "계란말이", spy: "계란찜" },
    { word: "만두", spy: "물만두" },
    { word: "돈가스", spy: "생선가스" },
    { word: "카레라이스", spy: "볶음밥" },
    { word: "비빔밥", spy: "덮밥" },
    { word: "샌드위치", spy: "토스트" },
    { word: "된장국", spy: "미역국" },
    { word: "불고기", spy: "제육볶음" },
    { word: "어묵", spy: "소시지" },
  ],
  "🍭 간식": [
    { word: "아이스크림", spy: "빙수" },
    { word: "사탕", spy: "젤리" },
    { word: "초콜릿", spy: "캐러멜" },
    { word: "과자", spy: "쿠키" },
    { word: "케이크", spy: "빵" },
    { word: "도넛", spy: "와플" },
    { word: "팝콘", spy: "뻥튀기" },
    { word: "푸딩", spy: "요거트" },
    { word: "솜사탕", spy: "막대사탕" },
    { word: "마카롱", spy: "머핀" },
    { word: "붕어빵", spy: "호떡" },
    { word: "식혜", spy: "수정과" },
    { word: "떡", spy: "약과" },
    { word: "초코파이", spy: "카스테라" },
    { word: "슬러시", spy: "주스" },
    { word: "누룽지", spy: "숭늉" },
  ],
  "🍎 과일·채소": [
    { word: "사과", spy: "배" },
    { word: "바나나", spy: "참외" },
    { word: "딸기", spy: "방울토마토" },
    { word: "수박", spy: "멜론" },
    { word: "포도", spy: "체리" },
    { word: "귤", spy: "오렌지" },
    { word: "복숭아", spy: "자두" },
    { word: "키위", spy: "망고" },
    { word: "감", spy: "대추" },
    { word: "당근", spy: "무" },
    { word: "오이", spy: "애호박" },
    { word: "양파", spy: "마늘" },
    { word: "감자", spy: "고구마" },
    { word: "배추", spy: "상추" },
    { word: "옥수수", spy: "완두콩" },
    { word: "버섯", spy: "콩나물" },
  ],
  "✏️ 학용품": [
    { word: "연필", spy: "볼펜" },
    { word: "지우개", spy: "수정테이프" },
    { word: "가위", spy: "풀" },
    { word: "자", spy: "각도기" },
    { word: "공책", spy: "스케치북" },
    { word: "책가방", spy: "필통" },
    { word: "색연필", spy: "크레파스" },
    { word: "물감", spy: "사인펜" },
    { word: "칠판", spy: "화이트보드" },
    { word: "컴퍼스", spy: "삼각자" },
    { word: "도시락", spy: "물통" },
    { word: "교과서", spy: "문제집" },
    { word: "색종이", spy: "도화지" },
    { word: "클립", spy: "스테이플러" },
  ],
  "🚗 탈것": [
    { word: "자동차", spy: "트럭" },
    { word: "버스", spy: "택시" },
    { word: "자전거", spy: "오토바이" },
    { word: "기차", spy: "지하철" },
    { word: "비행기", spy: "헬리콥터" },
    { word: "배", spy: "잠수함" },
    { word: "소방차", spy: "구급차" },
    { word: "경찰차", spy: "순찰차" },
    { word: "포크레인", spy: "불도저" },
    { word: "킥보드", spy: "인라인" },
    { word: "관람차", spy: "회전목마" },
    { word: "요트", spy: "보트" },
    { word: "로켓", spy: "우주선" },
    { word: "마차", spy: "수레" },
  ],
  "👩‍🚒 직업": [
    { word: "의사", spy: "간호사" },
    { word: "선생님", spy: "교수님" },
    { word: "경찰관", spy: "소방관" },
    { word: "요리사", spy: "제빵사" },
    { word: "가수", spy: "배우" },
    { word: "화가", spy: "만화가" },
    { word: "운동선수", spy: "코치" },
    { word: "농부", spy: "어부" },
    { word: "군인", spy: "장군" },
    { word: "우주비행사", spy: "조종사" },
    { word: "미용사", spy: "이발사" },
    { word: "수의사", spy: "사육사" },
    { word: "택배기사", spy: "우체부" },
    { word: "과학자", spy: "발명가" },
    { word: "마술사", spy: "광대" },
    { word: "유튜버", spy: "아나운서" },
  ],
  "⚽ 운동·놀이": [
    { word: "축구", spy: "농구" },
    { word: "야구", spy: "피구" },
    { word: "배구", spy: "족구" },
    { word: "수영", spy: "다이빙" },
    { word: "태권도", spy: "유도" },
    { word: "줄넘기", spy: "훌라후프" },
    { word: "술래잡기", spy: "숨바꼭질" },
    { word: "달리기", spy: "이어달리기" },
    { word: "탁구", spy: "배드민턴" },
    { word: "스키", spy: "썰매" },
    { word: "보드게임", spy: "카드게임" },
    { word: "공기놀이", spy: "딱지치기" },
    { word: "그네", spy: "시소" },
    { word: "미끄럼틀", spy: "정글짐" },
  ],
  "🏫 장소": [
    { word: "학교", spy: "유치원" },
    { word: "병원", spy: "약국" },
    { word: "놀이공원", spy: "동물원" },
    { word: "도서관", spy: "서점" },
    { word: "마트", spy: "시장" },
    { word: "영화관", spy: "공연장" },
    { word: "수영장", spy: "목욕탕" },
    { word: "공원", spy: "운동장" },
    { word: "바다", spy: "계곡" },
    { word: "산", spy: "들판" },
    { word: "박물관", spy: "미술관" },
    { word: "문구점", spy: "편의점" },
    { word: "분식집", spy: "식당" },
    { word: "캠핑장", spy: "펜션" },
    { word: "교실", spy: "강당" },
    { word: "놀이터", spy: "모래밭" },
  ],
  "🌈 자연·날씨": [
    { word: "비", spy: "눈" },
    { word: "무지개", spy: "노을" },
    { word: "구름", spy: "안개" },
    { word: "바람", spy: "태풍" },
    { word: "천둥", spy: "번개" },
    { word: "해", spy: "달" },
    { word: "별", spy: "유성" },
    { word: "강", spy: "호수" },
    { word: "꽃", spy: "나무" },
    { word: "단풍", spy: "낙엽" },
    { word: "고드름", spy: "서리" },
    { word: "이슬", spy: "물방울" },
    { word: "봄", spy: "가을" },
    { word: "여름", spy: "겨울" },
  ],
  "🏠 생활용품": [
    { word: "숟가락", spy: "젓가락" },
    { word: "컵", spy: "그릇" },
    { word: "칫솔", spy: "치약" },
    { word: "비누", spy: "샴푸" },
    { word: "수건", spy: "손수건" },
    { word: "베개", spy: "이불" },
    { word: "의자", spy: "소파" },
    { word: "시계", spy: "달력" },
    { word: "우산", spy: "장화" },
    { word: "안경", spy: "선글라스" },
    { word: "가방", spy: "지갑" },
    { word: "휴대폰", spy: "태블릿" },
    { word: "텔레비전", spy: "컴퓨터" },
    { word: "냉장고", spy: "세탁기" },
    { word: "빗자루", spy: "걸레" },
    { word: "거울", spy: "빗" },
  ],
};
