/* =========================================================
   서울 겨울 가족여행 플래너 — 데이터
   2027.1.19(화) 저녁 ~ 1.23(토) / 대전 출발 자차 / 5인 가족
   status: 'ok'     = 2026년 기준 운영 확인됨 (2027.1 재확인 권장)
           'verify' = 2027.1 운영·라인업·요금 확정 전 (공식 링크로 재확인 필수)
   cost: 1인 요금(원). a=성인, t=청소년(중·고), c=어린이(초등). 0=무료
   ages: 아이별 추천도 1~3 (k1=중2, k2=초6, k3=초3)
   좌표는 지도 표시용 근사값 — 길찾기는 카카오맵 버튼으로 실측
   ========================================================= */
window.TRIP = {
  meta: {
    title: '서울 겨울 가족여행',
    subtitle: '2027.1.19(화) 저녁 → 1.23(토) · 대전 출발 자차 · 5인',
    days: [
      { id: 'd0', date: '2027-01-19', dow: '화', label: 'D0 · 1/19(화)', hint: '저녁 출발 → 체크인 → 가벼운 야경', start: '18:00' },
      { id: 'd1', date: '2027-01-20', dow: '수', label: 'D1 · 1/20(수)', hint: '첫 온전한 하루', start: '09:00' },
      { id: 'd2', date: '2027-01-21', dow: '목', label: 'D2 · 1/21(목)', hint: '원정 또는 서울 집중', start: '09:00' },
      { id: 'd3', date: '2027-01-22', dow: '금', label: 'D3 · 1/22(금)', hint: '마지막 온전한 하루', start: '09:00' },
      { id: 'd4', date: '2027-01-23', dow: '토', label: 'D4 · 1/23(토)', hint: '오전 일정 → 대전 귀가', start: '09:30' }
    ],
    home: { name: '대전(출발·귀가)', lat: 36.3504, lng: 127.3845 }
  },

  members: [
    { id: 'dad', name: '아빠', emoji: '👨' },
    { id: 'mom', name: '엄마', emoji: '👩' },
    { id: 'k1', name: '첫째(중2)', emoji: '🧑' },
    { id: 'k2', name: '둘째(초6)', emoji: '👦' },
    { id: 'k3', name: '셋째(초3)', emoji: '👧' }
  ],

  types: [
    { id: 'must', label: '필수', emoji: '⭐', color: '#e8842c' },
    { id: 'show', label: '공연', emoji: '🎭', color: '#b04a8c' },
    { id: 'exp', label: '체험', emoji: '🎯', color: '#2e8b6e' },
    { id: 'museum', label: '박물관·과학관', emoji: '🏛️', color: '#3b63b8' },
    { id: 'spot', label: '명소·야경', emoji: '🌃', color: '#5a5fc2' },
    { id: 'food', label: '맛집', emoji: '🍜', color: '#c9552f' },
    { id: 'stay', label: '숙소', emoji: '🏨', color: '#7a7a8a' },
    { id: 'far', label: '근교 원정', emoji: '🚗', color: '#2c8fa8' },
    { id: 'shop', label: '쇼핑·휴식', emoji: '🛍️', color: '#8b6f3b' }
  ],

  regions: [
    { id: 'gwanghwamun', label: '광화문·종로·명동' },
    { id: 'yongsan', label: '용산·남산' },
    { id: 'yeouido', label: '여의도·마포' },
    { id: 'jamsil', label: '잠실·삼성' },
    { id: 'seongsu', label: '성수·뚝섬·동대문' },
    { id: 'gwacheon', label: '과천·광명' },
    { id: 'gimpo', label: '김포공항' },
    { id: 'ganghwa', label: '강화도' },
    { id: 'incheon', label: '인천(개항장·월미·송도)' },
    { id: 'yeongjong', label: '영종도' },
    { id: 'paju', label: '파주·DMZ' }
  ],

  places: [
    /* ───────── 필수 ───────── */
    { id: 'nmk', name: '국립중앙박물관', type: 'must', types: ['must','museum'], region: 'yongsan', lat: 37.5240, lng: 126.9803,
      oh: ['10:00','18:00'], ohByDow: { '수':['10:00','21:00'], '토':['10:00','21:00'] },
      dur: 180, cost: { a: 0, t: 0, c: 0, note: '상설전시 무료 · 특별전 유료' },
      hours: '월·화·목·금·일 10:00~18:00 / 수·토 10:00~21:00(야간개장)', closed: '1/1, 설·추석 당일, 4·11월 첫째 월요일 → 여행기간 정상 운영',
      reserve: 'required', reserveNote: '어린이박물관 회차(80분, 하루 5회) 예약 필수 — 관람일 14일 전 0시 오픈, 1회 최대 5매. 1/20 관람 = 1/6 0시 오픈',
      indoor: true, parking: '지하 주차장(유료, 2시간 2,000원 수준 → 현장 확인)',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '국내 최대 박물관. 반가사유상(사유의 방)·디지털 실감영상관은 대전에서 볼 수 없는 규모',
      tips: '수요일은 21시까지 야간개장이라 D1(수)에 배치하면 여유 있음. 사유의 방 → 디지털 실감영상관 → 어린이박물관 순 추천. 박물관 내 푸드코트·카페 있음. 극장 "용" 공연도 확인',
      links: { official: 'https://www.museum.go.kr', booking: 'https://www.museum.go.kr/MUSEUM/contents/M0104010000.do?schM=child&act=intro' },
      status: 'ok', tags: ['무료','실내','필수','예약'] },

    /* ───────── 공연 ───────── */
    { id: 'nanta', name: '난타 (명동 난타극장)', type: 'show', region: 'gwanghwamun', lat: 37.5638, lng: 126.9855,
      dur: 100, cost: { a: 50000, t: 50000, c: 50000, note: '좌석등급별 4~6만원대, 할인 티켓 사이트 활용' },
      hours: '매일 공연 · 회차 시간표는 예매처 확인 (보통 17:00 / 20:00)', closed: '—',
      reserve: 'required', reserveNote: '인터파크·예스24·타임티켓 등에서 사전 예매',
      indoor: true, parking: '명동 인근 공영주차장(혼잡) — 숙소에 차 두고 지하철 권장',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '대사 없는 넌버벌 퍼포먼스, 초3부터 어른까지 전원 만족도 높은 검증된 공연',
      tips: '현재 공연 확정 기간은 2026.12.31까지 → 2027.1 연장 여부 예매처에서 확인. 앞좌석은 물 튐 주의(재미 요소)',
      links: { official: 'https://www.nanta.co.kr', booking: 'https://tickets.interpark.com/search?keyword=%EB%82%9C%ED%83%80' },
      status: 'verify', verifyNote: '2027년 1월 공연 일정 확정 전', tags: ['공연','실내','예약'] },

    { id: 'painters', name: '페인터즈 (광화문 전용관)', type: 'show', region: 'gwanghwamun', lat: 37.5647, lng: 126.9683,
      dur: 90, cost: { a: 60000, t: 60000, c: 60000, note: 'VIP 7만 / R 6만 / S 5만 (할인 티켓 흔함)' },
      hours: '매일 14:00 / 17:00 / 20:00 (75분)', closed: '—',
      reserve: 'required', reserveNote: '예매처 사전 예약',
      indoor: true, parking: '경향아트힐 인근 유료주차 — 지하철(시청·서대문) 권장',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '눈앞에서 그림이 완성되는 라이브 드로잉 + 댄스, 미술 좋아하는 아이에게 특히 강함',
      tips: '17시 회차 보고 명동에서 저녁 먹는 동선이 자연스러움. 현재 확정 기간 2026.11.30 → 연장 확인',
      links: { official: 'https://www.mcst.go.kr/site/s_culture/culture/cultureView.jsp?pSeq=44112&pRo=2', booking: 'https://ticket.yes24.com/New/Perf/Detail/Detail.aspx?IdPerf=49034' },
      status: 'verify', verifyNote: '2027년 1월 공연 연장 여부 확인 필요', tags: ['공연','실내','예약'] },

    { id: 'sejong', name: '세종문화회관 겨울방학 가족공연', type: 'show', region: 'gwanghwamun', lat: 37.5722, lng: 126.9760,
      dur: 120, cost: { a: 50000, t: 50000, c: 50000, note: '작품별 상이 (3~8만원)' },
      hours: '공연별', closed: '—',
      reserve: 'required', reserveNote: '겨울방학 시즌 라인업은 보통 10~11월 공개 → 그때 예매',
      indoor: true, parking: '세종문화회관 지하주차장(유료)',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '광화문 한복판 대극장 경험 자체가 특별. 방학 시즌 어린이·가족 뮤지컬 편성이 많음',
      tips: '광화문광장·청계천과 묶어 저녁 동선으로. 라인업 미확정이므로 "공연 슬롯"으로 예약해두고 작품 결정',
      links: { official: 'https://www.sejongpac.or.kr' },
      status: 'verify', verifyNote: '2027.1 라인업 미공개', tags: ['공연','실내','예약'] },

    { id: 'charlotte', name: '샤롯데씨어터 대형 뮤지컬 (잠실)', type: 'show', region: 'jamsil', lat: 37.5110, lng: 127.0982,
      dur: 170, cost: { a: 120000, t: 120000, c: 120000, note: '대형 뮤지컬 R석 기준 12~16만원, 5인이면 60만원+ (예산 판단 필요)' },
      hours: '평일 19:30 / 주말 14:00·18:30 (작품별)', closed: '월요일 공연 없음이 일반적',
      reserve: 'required', reserveNote: '인기작은 2~3개월 전 오픈, 오픈일 알림 설정',
      indoor: true, parking: '롯데월드몰 주차(유료) — 관람 시 할인 확인',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '대전에서는 볼 수 없는 오리지널 규모의 뮤지컬 전용극장',
      tips: '중2·초6 중심 선택지. 초3에게는 3시간 관람이 부담될 수 있어 작품 러닝타임 확인. 서울스카이·롯데월드몰과 하루로 묶기 좋음',
      links: { official: 'https://www.charlottetheater.co.kr' },
      status: 'verify', verifyNote: '2027.1 작품 미확정', tags: ['공연','실내','예약','고비용'] },

    { id: 'ntok', name: '국립극장 (남산) 겨울 공연', type: 'show', region: 'yongsan', lat: 37.5528, lng: 127.0040,
      dur: 120, cost: { a: 40000, t: 40000, c: 40000, note: '국립단체 공연은 2~5만원대, 가족 할인 있음' },
      hours: '공연별', closed: '—',
      reserve: 'required', reserveNote: '국립극장 홈페이지 예매',
      indoor: true, parking: '국립극장 주차장(유료, 넉넉)',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '국립창극단·국립무용단·국립국악관현악단 — 전통 기반 공연을 최고 수준으로',
      tips: '남산타워와 같은 산자락. 겨울방학 어린이 대상 창극/국악 공연이 편성되면 초3에게도 좋음',
      links: { official: 'https://www.ntok.go.kr' },
      status: 'verify', verifyNote: '2027.1 라인업 미공개', tags: ['공연','실내','예약'] },

    { id: 'sac', name: '예술의전당 (서초)', type: 'show', region: 'jamsil', lat: 37.4787, lng: 127.0125,
      dur: 120, cost: { a: 50000, t: 50000, c: 50000, note: '공연별 상이' },
      hours: '공연별', closed: '—',
      reserve: 'required', reserveNote: 'SAC 티켓 예매',
      indoor: true, parking: '예술의전당 주차장(유료)',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '음악당·오페라극장·한가람미술관이 한 곳에 — 클래식·전시 겸하기 좋음',
      tips: '겨울방학 어린이 클래식 콘서트(해설 있는 공연)가 있으면 초3도 무난. 서울 남단이라 과천과학관과 묶으면 동선 좋음',
      links: { official: 'https://www.sac.or.kr' },
      status: 'verify', verifyNote: '2027.1 라인업 미공개', tags: ['공연','실내','예약'] },

    /* ───────── 체험 ───────── */
    { id: 'hikr', name: '하이커 그라운드 (HiKR Ground)', type: 'exp', region: 'gwanghwamun', lat: 37.5687, lng: 126.9820,
      oh: ['10:00','21:00'],
      dur: 90, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '1·5층 10:00~21:00 / 2~4층 10:00~19:00', closed: '2~4층 월요일 휴관 → 여행기간 정상',
      reserve: 'none', reserveNote: '예약 없이 입장. 한국어 해설 투어 10:30·15:30(40분)',
      indoor: true, parking: '인근 공영주차장 — 청계천·광화문과 도보 연계',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '한국관광공사 K-컬처 체험관. K-pop 뮤직비디오 촬영 체험(XR 스튜디오)을 무료로',
      tips: '중2가 가장 좋아할 곳. 촬영 영상은 QR로 다운로드. 청계천 산책 → 광장시장 저녁으로 이어지는 동선',
      links: { official: 'https://hikr.visitkorea.or.kr' },
      status: 'ok', tags: ['무료','실내','K-pop'] },

    { id: 'assembly', name: '국회의사당 참관 (본회의장)', type: 'exp', region: 'yeouido', lat: 37.5318, lng: 126.9140,
      closedDow: ['일'], closedDates: ['2027-01-23'], oh: ['10:00','18:00'],
      dur: 70, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '평일 10~17시 정시 6회 / 토 10~12시 3회(2026년 기준 매월 1·2·3주 토요일만)', closed: '일요일 · 1/23(넷째 토)는 미운영 → 평일 배치',
      reserve: 'required', reserveNote: '통합예약 사이트: 90일 전~전일까지, 전원 신분증 지참(학생은 학생증/주민등록초본 등)',
      indoor: true, parking: '국회 방문자 주차 가능(안내 확인)',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '본회의장 의장석 체험·전자투표 체험. 사회 교과와 직결, 대전에서는 불가능한 경험',
      tips: '10시 회차 → 인접 KBS On → 더현대 점심으로 여의도 반나절 완성. 국회박물관도 무료',
      links: { official: 'https://www.assembly.go.kr/portal/main/contents.do?menuNo=600069', booking: 'https://reservation.assembly.go.kr' },
      status: 'ok', tags: ['무료','실내','예약','교육'] },

    { id: 'kbson', name: 'KBS On 견학홀 (여의도)', type: 'exp', region: 'yeouido', lat: 37.5245, lng: 126.9170,
      closedDow: ['토','일'], oh: ['10:00','17:00'],
      dur: 70, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '해설 투어 10·11·13·14·15·16시', closed: '주말·공휴일 휴관(확인)',
      reserve: 'required', reserveNote: '최소 5일 전 홈페이지·전화 예약',
      indoor: true, parking: 'KBS 유료주차',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '뉴스 앵커 체험·가상 스튜디오 등 방송국 뒷무대를 해설과 함께',
      tips: '국회 참관과 도보 15분. 사진 촬영 가능 구간 많음',
      links: { official: 'https://office.kbs.co.kr/kbson' },
      status: 'verify', verifyNote: '2027.1 운영 일정·예약 오픈 확인', tags: ['무료','실내','예약'] },

    { id: 'plaza_skate', name: '서울광장 스케이트장', type: 'exp', region: 'gwanghwamun', lat: 37.5657, lng: 126.9780,
      oh: ['10:00','21:30'],
      dur: 80, cost: { a: 1000, t: 1000, c: 1000, note: '1시간 1,000원 (스케이트·헬멧 대여 포함)' },
      hours: '일~금 10:00~21:30 / 토 10:00~23:00 (25-26 시즌: 12/19~2/8)', closed: '시즌 외',
      reserve: 'recommended', reserveNote: '온라인 사전 예매 회차제(seoulskate.kr), 현장 판매 소량',
      indoor: false, parking: '시청 인근 공영주차 — 대중교통 권장',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '시청 앞 야외 링크에서 1,000원으로 스케이트. 야간 도심 야경 속 스케이트는 대전에 없음',
      tips: '저녁 회차가 분위기 최고. 장갑 필수(없으면 입장 불가). 26-27 시즌 운영 기간은 12월 초 발표',
      links: { official: 'https://seoulskate.kr' },
      status: 'verify', verifyNote: '26-27 시즌 운영기간 미발표', tags: ['저비용','야외','겨울한정'] },

    { id: 'ttukseom_sled', name: '뚝섬 한강공원 눈썰매장', type: 'exp', region: 'seongsu', lat: 37.5300, lng: 127.0670,
      oh: ['10:00','17:00'],
      dur: 120, cost: { a: 6000, t: 6000, c: 6000, note: '입장 6,000원 균일 (놀이기구 별도)' },
      hours: '10:00~17:00, 13~14시 정비 (25-26: 12/31~2/18)', closed: '기간 중 휴무 없음',
      reserve: 'none', reserveNote: '현장 구매',
      indoor: false, parking: '뚝섬한강공원 주차장(유료)',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '한강 옆 대형 눈썰매 슬로프 + 눈놀이동산',
      tips: '오전 10시 개장 직후가 한산. 방수 바지·장갑 필수. 성수동 카페·팝업과 묶으면 중2도 만족',
      links: { official: 'https://hangang.seoul.go.kr/www/contents/757.do?mid=506' },
      status: 'verify', verifyNote: '26-27 시즌 운영기간 미발표', tags: ['야외','겨울한정'] },

    { id: 'lw_icerink', name: '롯데월드 아이스링크', type: 'exp', region: 'jamsil', lat: 37.5110, lng: 127.0985,
      oh: ['10:00','21:30'],
      dur: 120, cost: { a: 19000, t: 19000, c: 19000, note: '평일 입장+대여 세트 19,000원 (3시간)' },
      hours: '10:00~21:30 내외 (요일별 상이)', closed: '—',
      reserve: 'none', reserveNote: '현장·온라인 모두 가능',
      indoor: true, parking: '롯데월드몰 주차(유료)',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '실내 대형 링크 — 한파에도 스케이트 가능, 롯데월드 어드벤처 내부 풍경',
      tips: '서울광장 스케이트장이 운영 안 하거나 너무 추운 날의 대체안',
      links: { official: 'https://adventure.lotteworld.com/icerink' },
      status: 'ok', tags: ['실내'] },

    { id: 'lotteworld', name: '롯데월드 어드벤처', type: 'exp', region: 'jamsil', lat: 37.5111, lng: 127.0981,
      oh: ['10:00','21:00'],
      dur: 420, cost: { a: 62000, t: 54000, c: 47000, note: '종일권 기준 (온라인 할인 흔함). 5인 약 27만원' },
      hours: '10:00~21:00 내외', closed: '—',
      reserve: 'recommended', reserveNote: '온라인 할인권 사전 구매, 매직패스 별도',
      indoor: true, parking: '롯데월드 주차(유료)',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '실내 테마파크라 겨울에 최적. 대전엔 없는 규모',
      tips: '하루를 통째로 쓰는 카드. 평일이라 대기 짧음. 저녁 퍼레이드까지 보면 밤 9시',
      links: { official: 'https://adventure.lotteworld.com' },
      status: 'ok', tags: ['실내','종일','고비용'] },

    { id: 'kidzania', name: '키자니아 서울 (잠실)', type: 'exp', region: 'jamsil', lat: 37.5108, lng: 127.0973,
      oh: ['10:00','20:00'],
      dur: 300, cost: { a: 20000, t: 45000, c: 55000, note: '1부/2부 회차제. 어린이 5~6만, 보호자 2만 내외' },
      hours: '1부 10:00~15:00 / 2부 15:30~20:00 (평일 상이)', closed: '—',
      reserve: 'required', reserveNote: '온라인 예매 필수 (평일 회차 여유)',
      indoor: true, parking: '롯데월드몰 주차',
      ages: { k1: 1, k2: 2, k3: 3 },
      why: '직업 체험 테마파크 — 초3에게는 최고, 초6은 상한선, 중2는 시들',
      tips: '초3 중심 선택지. 중2는 같은 시간 롯데월드몰·서울스카이로 분리 동선을 짜는 것도 방법',
      links: { official: 'https://www.kidzania.co.kr' },
      status: 'ok', tags: ['실내','예약','초등'] },

    { id: 'coex_aqua', name: '코엑스 아쿠아리움', type: 'exp', region: 'jamsil', lat: 37.5130, lng: 127.0590,
      oh: ['10:00','20:00'],
      dur: 120, cost: { a: 35000, t: 31000, c: 29000, note: '온라인 할인 시 20% 내외' },
      hours: '10:00~20:00', closed: '—',
      reserve: 'recommended', reserveNote: '온라인 할인권',
      indoor: true, parking: '코엑스 주차(유료)',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '도심 지하 대형 수족관, 별마당도서관과 한 건물',
      tips: '별마당도서관(무료) → 아쿠아리움 → 코엑스몰 식사. D4 귀가 전 오전 코스로 적합(잠실에서 경부고속도로 진입 용이)',
      links: { official: 'https://www.coexaqua.com' },
      status: 'ok', tags: ['실내'] },

    { id: 'seoulsky', name: '서울스카이 (롯데월드타워 전망대)', type: 'exp', region: 'jamsil', lat: 37.5126, lng: 127.1025,
      oh: ['10:00','22:00'],
      dur: 90, cost: { a: 33000, t: 33000, c: 29000, note: '2026.4 기준 33,000원. 5인 약 15만원. 패스트패스 59,000' },
      hours: '10:00~22:00 (입장 마감 21:00)', closed: '—',
      reserve: 'recommended', reserveNote: '일몰 시간대 온라인 예매 권장',
      indoor: true, parking: '롯데월드몰 주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '555m 초고층 전망대, 스카이데크(유리바닥). 1월 일몰 17:30 전후 입장이 최고',
      tips: '16:45 입장 → 낮·일몰·야경 3종 세트. 겨울은 미세먼지 없는 날 골라서(당일 판단 가능한 유연 슬롯)',
      links: { official: 'https://seoulsky.lotteworld.com' },
      status: 'ok', tags: ['실내','야경'] },

    { id: 'bluehouse', name: '청와대 관람', type: 'exp', region: 'gwanghwamun', lat: 37.5866, lng: 126.9748,
      dur: 120, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '회차제 (경복궁 동편주차장 "만남의장소" 집결 → 셔틀)', closed: '운영 정책 변동 가능',
      reserve: 'required', reserveNote: '공식 예약 사이트, 실물 신분증 필수',
      indoor: false, parking: '경복궁 동편주차장',
      ages: { k1: 3, k2: 2, k3: 2 },
      why: '본관·영빈관·녹지원 — 관람 가능 시기는 역사적으로 한정적',
      tips: '대통령실 복귀 논의로 관람 범위·가능 여부가 계속 바뀜. 예약 페이지에서 1월 일정이 열리는지 확인 후 결정. 경복궁·북촌과 묶기',
      links: { official: 'https://www.opencheongwadae.kr' },
      status: 'verify', verifyNote: '개방 정책 변동 — 2027.1 예약 가능 여부 확인', tags: ['무료','예약','야외'] },

    { id: 'namsan', name: '남산케이블카 + N서울타워', type: 'exp', region: 'yongsan', lat: 37.5512, lng: 126.9882,
      oh: ['10:00','23:00'],
      dur: 120, cost: { a: 15000, t: 15000, c: 11500, note: '케이블카 왕복 성인 15,000 / 어린이 11,500 (전망대 입장 별도 2만 내외, 선택)' },
      hours: '케이블카 10:00~23:00', closed: '—',
      reserve: 'none', reserveNote: '현장 구매 (주말 대기 김)',
      indoor: false, parking: '케이블카 승강장 주차 매우 협소 — 명동에서 도보 or 남산순환버스',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '서울 대표 야경. 사랑의 자물쇠 광장은 전망대 안 가도 무료',
      tips: '명동 저녁 → 케이블카 → 야경 → 숙소 순. 전망대 입장은 선택(자물쇠 광장만으로도 충분)',
      links: { official: 'https://www.cablecar.co.kr' },
      status: 'ok', tags: ['야경','야외'] },

    { id: 'cruise', name: '한강 유람선 (이랜드크루즈, 여의도)', type: 'exp', region: 'yeouido', lat: 37.5283, lng: 126.9330,
      dur: 80, cost: { a: 18000, t: 18000, c: 13000, note: '기본 크루즈 기준. 뮤직·불꽃 크루즈는 3만원대' },
      hours: '주간·야간 회차 (겨울 축소 운항)', closed: '기상 악화 시 결항',
      reserve: 'recommended', reserveNote: '온라인 예매',
      indoor: true, parking: '여의도한강공원 주차(유료)',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '한강 다리·63빌딩·남산타워를 물 위에서. 실내 객실 있어 겨울도 가능',
      tips: '겨울 야간 크루즈는 매우 추우니 실내석. 더현대 서울과 묶기',
      links: { official: 'https://www.elandcruise.com' },
      status: 'verify', verifyNote: '겨울 운항 시간표 확인', tags: ['야경','실내'] },

    /* ───────── 박물관·과학관 ───────── */
    { id: 'warmemorial', name: '전쟁기념관 (어린이박물관 포함)', type: 'museum', region: 'yongsan', lat: 37.5365, lng: 126.9770,
      closedDow: ['월'], oh: ['09:30','18:00'],
      dur: 120, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '09:30~18:00', closed: '월요일 → 여행기간 정상',
      reserve: 'recommended', reserveNote: '어린이박물관은 회차 예약(홈페이지) 확인',
      indoor: 'mixed', parking: '기념관 주차장(유료, 넉넉)',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '야외 전시장의 실물 전투기·탱크·함정 모형. 국립중앙박물관과 차 10분',
      tips: '국립중앙박물관과 같은 날 세트로. 야외 전시장은 30분 정도, 방한 필수',
      links: { official: 'https://www.warmemo.or.kr' },
      status: 'ok', tags: ['무료','실내'] },

    { id: 'gwacheon_sci', name: '국립과천과학관', type: 'museum', region: 'gwacheon', lat: 37.4351, lng: 126.9977,
      closedDow: ['월'], oh: ['09:30','17:30'],
      dur: 300, cost: { a: 4000, t: 2000, c: 2000, note: '상설전시 성인 4,000 / 청소년·어린이 2,000. 천체투영관 2,000 별도' },
      hours: '09:30~17:30', closed: '월요일 → 여행기간 정상 / 1월 1일',
      reserve: 'recommended', reserveNote: '천체투영관·스페이스월드 등 회차 프로그램은 온라인 예약 권장',
      indoor: 'mixed', parking: '과학관 주차장(유료, 넉넉)',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '대전 국립중앙과학관과는 다른 구성 — 천체투영관(돔), 자연사관, 첨단기술관 규모가 다름',
      tips: '"대전에도 과학관 있잖아"에 대한 답: 천체투영관·야외 우주체험 시설이 다름. 반나절 이상 잡을 것. 서울 남부라 예술의전당·코엑스와 동선',
      links: { official: 'https://www.sciencecenter.go.kr', booking: 'https://www.sciencecenter.go.kr/scipia/schedules?ACADEMY_CD=ACD007' },
      status: 'ok', tags: ['저비용','실내','과학'] },

    { id: 'aviation', name: '국립항공박물관 (김포공항)', type: 'museum', region: 'gimpo', lat: 37.5665, lng: 126.7975,
      closedDow: ['월'], oh: ['10:00','18:00'],
      dur: 150, cost: { a: 0, t: 0, c: 0, note: '입장 무료 · 체험(조종관제·블랙이글스 탑승·기내훈련) 3~5천원' },
      hours: '10:00~18:00', closed: '월요일 → 여행기간 정상',
      reserve: 'recommended', reserveNote: '체험 프로그램은 당일 현장 or 온라인 선착순 — 오픈 직후 도착 권장',
      indoor: true, parking: '박물관 주차장(유료)',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '실물 항공기 전시 + 조종 시뮬레이터 체험, 김포공항 활주로 조망',
      tips: '강화도·인천 원정 가는 길목(서울 서쪽)이라 원정일 아침 or 귀환길에 끼우기 좋음',
      links: { official: 'https://www.aviation.or.kr' },
      status: 'ok', tags: ['무료','실내','체험'] },

    { id: 'palace_museum', name: '국립고궁박물관', type: 'museum', region: 'gwanghwamun', lat: 37.5766, lng: 126.9748,
      oh: ['10:00','18:00'], ohByDow: { '수':['10:00','21:00'], '토':['10:00','21:00'] },
      dur: 80, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '10:00~18:00 (수·토 21:00)', closed: '1/1, 설·추석 당일',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '경복궁 주차장',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '조선 왕실 유물 — 어가·왕의 옥새·자격루. 경복궁과 바로 연결',
      tips: '경복궁 관람 전에 들러 왕실 이야기를 알고 궁으로 들어가면 아이들 몰입도 상승',
      links: { official: 'https://www.gogung.go.kr' },
      status: 'ok', tags: ['무료','실내'] },

    { id: 'folk_museum', name: '국립민속박물관 (경복궁 내)', type: 'museum', region: 'gwanghwamun', lat: 37.5815, lng: 126.9787,
      oh: ['09:00','17:00'],
      dur: 80, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '09:00~17:00 (동절기)', closed: '1/1, 설·추석 당일',
      reserve: 'recommended', reserveNote: '어린이박물관은 회차 예약',
      indoor: 'mixed', parking: '경복궁 주차장',
      ages: { k1: 2, k2: 2, k3: 3 },
      why: '추억의 거리(1970년대 골목 재현)는 부모 세대와 아이가 함께 웃는 공간',
      tips: '경복궁 입장권으로 무료 관람. 추억의 거리는 야외라 잠깐',
      links: { official: 'https://www.nfm.go.kr' },
      status: 'ok', tags: ['무료'] },

    { id: 'mmca', name: '국립현대미술관 서울', type: 'museum', region: 'gwanghwamun', lat: 37.5788, lng: 126.9804,
      oh: ['10:00','18:00'],
      dur: 90, cost: { a: 2000, t: 0, c: 0, note: '상설 무료, 기획전 2,000원 (만 24세 이하 무료)' },
      hours: '10:00~18:00 (수·토 21:00)', closed: '1/1, 설·추석 당일',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '미술관 주차(유료)',
      ages: { k1: 3, k2: 2, k3: 1 },
      why: '경복궁 옆 현대미술 — 미디어아트 전시가 있으면 아이들도 즐김',
      tips: '중2 취향. 초3은 30분 한계 → 부모 1명과 분리 관람 가능한 동선(북촌 카페)',
      links: { official: 'https://www.mmca.go.kr' },
      status: 'ok', tags: ['저비용','실내'] },

    { id: 'seodaemun', name: '서대문형무소역사관', type: 'museum', region: 'gwanghwamun', lat: 37.5744, lng: 126.9560,
      closedDow: ['월'], oh: ['09:30','17:00'],
      dur: 90, cost: { a: 3000, t: 1500, c: 1000, note: '성인 3,000 / 청소년 1,500 / 어린이 1,000' },
      hours: '09:30~17:00 (동절기)', closed: '월요일 → 여행기간 정상',
      reserve: 'none', reserveNote: '—',
      indoor: 'mixed', parking: '독립공원 주차(유료)',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '독립운동 역사 현장 그 자체. 역사 교과 직결',
      tips: '감옥·사형장 등 무거운 공간이 있어 초3은 사전 설명 필요. 90분 이내로',
      links: { official: 'https://www.sscmc.or.kr/culture2' },
      status: 'ok', tags: ['저비용','역사'] },

    /* ───────── 명소·야경 ───────── */
    { id: 'gyeongbok', name: '경복궁 (한복 무료입장)', type: 'spot', region: 'gwanghwamun', lat: 37.5796, lng: 126.9770,
      closedDow: ['화'], oh: ['09:00','17:00'],
      dur: 120, cost: { a: 3000, t: 0, c: 0, note: '성인 3,000 / 만 24세 이하 무료 / 한복 착용 시 전원 무료' },
      hours: '09:00~17:00 (동절기, 입장 16:00 마감)', closed: '★ 화요일 휴궁 → 1/19(화) 불가, 1/20~23 가능',
      reserve: 'none', reserveNote: '수문장 교대식 10:00·14:00 무료 관람',
      indoor: false, parking: '경복궁 주차장(유료)',
      ages: { k1: 2, k2: 2, k3: 3 },
      why: '한복 대여(1~2만원)하고 궁 산책 — 사진 만족도 최상',
      tips: '한복 대여점은 경복궁역 주변 다수. 겨울 한복은 두루마기 추가. 수문장 교대식 시간 맞춰 입장. 야외라 한파 시 짧게',
      links: { official: 'https://royal.khs.go.kr/gyeongbokgung' },
      status: 'ok', tags: ['야외','저비용','사진'] },

    { id: 'gwanghwamun_sq', name: '광화문광장 + 청계천 야경', type: 'spot', region: 'gwanghwamun', lat: 37.5729, lng: 126.9769,
      dur: 60, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '상시', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '세종문화회관 주차 or 인근 공영',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '1월 서울빛초롱축제·광화문 마켓이 열리는 시기 — 청계천 등 조형물 야경',
      tips: '서울빛초롱축제는 보통 12월 중순~1월 초·중순 → 1/19 이후 지속 여부 확인. 광화문 광장 야외 스케이트장·눈썰매(윈터페스타)가 열리는 해도 있음',
      links: { official: 'https://www.seoul.go.kr' },
      status: 'verify', verifyNote: '2027 윈터페스타·빛초롱 기간 확인', tags: ['무료','야경','야외'] },

    { id: 'bukchon', name: '북촌한옥마을 + 익선동', type: 'spot', region: 'gwanghwamun', lat: 37.5826, lng: 126.9834,
      dur: 90, cost: { a: 0, t: 0, c: 0, note: '무료 (카페·간식 별도)' },
      hours: '북촌 한옥 거주지 관람 10:00~17:00 권장 (주민 배려)', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '북촌 공영주차장(협소) — 경복궁에서 도보',
      ages: { k1: 3, k2: 2, k3: 1 },
      why: '한옥 골목 사진 스팟 + 익선동 골목 카페·디저트',
      tips: '경복궁 → 북촌 → 익선동 도보 코스(1.5km). 초3은 지루할 수 있어 익선동 디저트로 보상',
      links: { official: 'https://hanok.seoul.go.kr' },
      status: 'ok', tags: ['무료','야외','사진'] },

    { id: 'deoksu', name: '덕수궁 + 돌담길 + 정동', type: 'spot', region: 'gwanghwamun', lat: 37.5658, lng: 126.9752,
      closedDow: ['월'], oh: ['09:00','21:00'],
      dur: 70, cost: { a: 1000, t: 0, c: 0, note: '성인 1,000 / 24세 이하 무료' },
      hours: '09:00~21:00', closed: '월요일 → 여행기간 정상',
      reserve: 'none', reserveNote: '석조전 내부는 예약 해설',
      indoor: false, parking: '시청 인근 공영',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '서양식 석조전이 있는 궁궐. 야간 개방으로 저녁 산책에 좋음. 페인터즈 전용관 도보 5분',
      tips: '페인터즈 17시 공연 전 낮 산책, 또는 공연 후 야간 돌담길',
      links: { official: 'https://royal.khs.go.kr/deoksugung' },
      status: 'ok', tags: ['저비용','야외','야경'] },

    { id: 'nodeul', name: '노들섬 (한강 야경)', type: 'spot', region: 'yongsan', lat: 37.5175, lng: 126.9590,
      dur: 50, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '상시 (시설 06:00~24:00)', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '노들섬 주차장(유료, 소규모)',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '한강 한가운데 섬에서 보는 여의도·용산 야경. 용산 숙소에서 차 10분',
      tips: 'D0 도착 저녁에 딱 30분만 — 첫날 "서울 왔다" 느낌 주기 용도. 강바람 매우 차가움',
      links: { official: 'https://nodeul.org' },
      status: 'ok', tags: ['무료','야경','야외'] },

    { id: 'ddp', name: 'DDP 동대문디자인플라자', type: 'spot', region: 'seongsu', lat: 37.5665, lng: 127.0092,
      oh: ['10:00','22:00'],
      dur: 80, cost: { a: 0, t: 0, c: 0, note: '건물·상설 무료, 기획전 유료' },
      hours: '10:00~20:00', closed: '월요일(전시) → 여행기간 정상',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: 'DDP 주차(유료)',
      ages: { k1: 3, k2: 2, k3: 2 },
      why: '자하 하디드의 비정형 건축, 미디어아트 서울라이트(겨울 시즌)',
      tips: '서울라이트 DDP는 보통 12월~1월 초 → 1/19 이후 지속 여부 확인. 신당동 떡볶이 도보 10분',
      links: { official: 'https://ddp.or.kr' },
      status: 'verify', verifyNote: '서울라이트 기간 확인', tags: ['무료','실내','야경'] },

    { id: 'seongsu', name: '성수동 팝업·카페 거리', type: 'spot', region: 'seongsu', lat: 37.5445, lng: 127.0560,
      dur: 120, cost: { a: 0, t: 0, c: 0, note: '무료 (카페·굿즈 별도)' },
      hours: '팝업별 11:00~20:00', closed: '—',
      reserve: 'none', reserveNote: '인기 팝업은 네이버 예약 대기',
      indoor: 'mixed', parking: '공영주차장 부족 — 뚝섬역 인근 유료',
      ages: { k1: 3, k2: 2, k3: 1 },
      why: '중2가 원하는 "요즘 서울" — 브랜드 팝업스토어·공장 개조 카페',
      tips: '방문 주 팝업 일정을 인스타·팝플리 등에서 검색해 카드에 메모. 뚝섬 눈썰매장과 같은 권역',
      links: { official: 'https://www.popply.co.kr' },
      status: 'ok', tags: ['무료','중학생'] },

    /* ───────── 맛집 ───────── */
    { id: 'gwangjang', name: '광장시장 먹거리 (빈대떡·마약김밥·육회)', type: 'food', region: 'gwanghwamun', lat: 37.5701, lng: 126.9996,
      oh: ['09:00','23:00'],
      dur: 70, cost: { a: 15000, t: 15000, c: 12000, note: '1인 1.2~1.5만원 선' },
      hours: '먹거리 골목 09:00~23:00 내외', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: 'mixed', parking: '시장 주차장(협소) — 종로5가역',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '전통시장 먹거리 골목 체험 — 서서 먹는 빈대떡·꼬마김밥은 아이들 최애',
      tips: '저녁 6시 이후 붐빔. 카드 가능한 곳 늘었지만 현금 소액 준비. 하이커그라운드·청계천에서 도보 15분',
      links: { official: 'https://map.naver.com/p/search/광장시장' },
      status: 'ok', tags: ['시장','저녁'] },

    { id: 'myeongdong_gyoja', name: '명동교자 (칼국수·만두)', type: 'food', region: 'gwanghwamun', lat: 37.5626, lng: 126.9856,
      oh: ['10:30','21:00'],
      dur: 50, cost: { a: 12000, t: 12000, c: 12000, note: '칼국수 1.2만원' },
      hours: '10:30~21:00', closed: '—',
      reserve: 'none', reserveNote: '대기 줄 있으나 회전 빠름',
      indoor: true, parking: '명동 공영주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '명동 대표 노포. 난타극장 도보 3분',
      tips: '마늘김치 강함 — 초3은 만두 위주. 난타 공연 전 이른 저녁으로',
      links: { official: 'https://map.naver.com/p/search/명동교자' },
      status: 'ok', tags: ['노포','점심','저녁'] },

    { id: 'hadongkwan', name: '하동관 (곰탕, 명동)', type: 'food', region: 'gwanghwamun', lat: 37.5648, lng: 126.9855,
      closedDow: ['일'], oh: ['07:00','16:00'],
      dur: 40, cost: { a: 16000, t: 16000, c: 16000, note: '곰탕 1.5~1.8만원' },
      hours: '07:00~16:00 (재료 소진 시 마감)', closed: '일요일',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '명동 공영주차',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '1939년 개업 곰탕 노포 — 아침·점심 전용',
      tips: '오후 4시 전 마감이니 점심 or 아침. 겨울 국물로 몸 녹이기',
      links: { official: 'https://map.naver.com/p/search/하동관 명동' },
      status: 'ok', tags: ['노포','점심'] },

    { id: 'tongin', name: '통인시장 엽전도시락', type: 'food', region: 'gwanghwamun', lat: 37.5800, lng: 126.9700,
      closedDow: ['월'], oh: ['11:00','16:00'],
      dur: 60, cost: { a: 10000, t: 10000, c: 8000, note: '엽전 10개 5,000원 단위 구매' },
      hours: '11:00~16:00 (도시락카페)', closed: '월요일 · 셋째 일요일',
      reserve: 'none', reserveNote: '—',
      indoor: 'mixed', parking: '시장 주차 협소 — 경복궁에서 도보 10분',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '엽전으로 반찬을 골라 담는 놀이형 점심 — 초등 만족도 최상',
      tips: '경복궁 서쪽. 운영 재개·시간은 방문 전 확인(운영 변동 이력 있음)',
      links: { official: 'https://map.naver.com/p/search/통인시장' },
      status: 'verify', verifyNote: '도시락카페 운영 여부 확인', tags: ['시장','점심'] },

    { id: 'sindang', name: '신당동 떡볶이 타운', type: 'food', region: 'seongsu', lat: 37.5652, lng: 127.0170,
      oh: ['11:00','22:00'],
      dur: 60, cost: { a: 12000, t: 12000, c: 12000, note: '즉석떡볶이 2인 기준 1.5~2만원' },
      hours: '11:00~22:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '가게별 제휴주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '즉석떡볶이 원조 거리 — DDP·동대문과 도보권',
      tips: 'DDP → 신당동 → 광장시장 저녁 동선 가능. 아이 3명 전원 만족 안전 카드',
      links: { official: 'https://map.naver.com/p/search/신당동 떡볶이타운' },
      status: 'ok', tags: ['점심','저녁'] },

    { id: 'nmk_food', name: '국립중앙박물관 푸드코트·카페', type: 'food', region: 'yongsan', lat: 37.5236, lng: 126.9790,
      oh: ['10:00','18:00'],
      dur: 50, cost: { a: 12000, t: 12000, c: 10000, note: '푸드코트 1인 1~1.3만원' },
      hours: '10:00~18:00 내외', closed: '박물관 휴관일',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '박물관 주차',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '박물관 관람 중간에 이동 없이 식사 — 시간 절약',
      tips: '12시 정각 붐빔 → 11:30 or 13:00',
      links: { official: 'https://www.museum.go.kr' },
      status: 'ok', tags: ['점심','실내'] },

    { id: 'mapo_galbi', name: '마포 돼지갈비 골목', type: 'food', region: 'yeouido', lat: 37.5397, lng: 126.9460,
      oh: ['11:30','22:00'],
      dur: 80, cost: { a: 20000, t: 20000, c: 15000, note: '1인 1.5~2만원' },
      hours: '11:30~22:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '가게 제휴주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '연탄 돼지갈비 노포 밀집 — 여의도·용산 숙소에서 가까운 든든한 저녁',
      tips: '여의도 일정 마무리 저녁으로',
      links: { official: 'https://map.naver.com/p/search/마포 돼지갈비' },
      status: 'ok', tags: ['저녁'] },

    { id: 'hyundai_food', name: '더현대 서울 푸드코트·디저트', type: 'food', region: 'yeouido', lat: 37.5259, lng: 126.9284,
      oh: ['10:30','20:00'],
      dur: 80, cost: { a: 15000, t: 15000, c: 12000, note: '1인 1.2~1.8만원' },
      hours: '10:30~20:00 (금~일 20:30)', closed: '월 1회 휴점(확인)',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '더현대 주차(구매 시 무료 시간)',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '실내 정원(사운즈포레스트)이 있는 백화점 — 지하 식품관·팝업이 중2 취향',
      tips: '국회·KBS 이후 점심. 겨울 크리스마스 빌리지 장식이 1월 초까지 남는 해도 있음',
      links: { official: 'https://www.thehyundaiseoul.com' },
      status: 'ok', tags: ['점심','실내','쇼핑'] },

    { id: 'noryangjin', name: '노량진수산시장 (직접 골라 회·매운탕)', type: 'food', region: 'yeouido', lat: 37.5138, lng: 126.9400,
      oh: ['11:00','22:00'],
      dur: 90, cost: { a: 30000, t: 25000, c: 20000, note: '5인 12~15만원 (회+매운탕+상차림비)' },
      hours: '24시간(소매 새벽~22시), 2층 식당 11:00~22:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '시장 주차(유료)',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '수산물 직접 고르고 위층에서 바로 먹는 체험형 식사',
      tips: '가격 흥정 필요. 회 안 먹는 아이가 있으면 튀김·매운탕으로. 여의도와 5분 거리',
      links: { official: 'https://www.susansijang.co.kr' },
      status: 'ok', tags: ['저녁','체험'] },

    { id: 'lwmall_food', name: '롯데월드몰 식당가', type: 'food', region: 'jamsil', lat: 37.5133, lng: 127.1040,
      oh: ['10:30','22:00'],
      dur: 70, cost: { a: 15000, t: 15000, c: 12000, note: '1인 1.2~1.8만원' },
      hours: '10:30~22:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '롯데월드몰 주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '서울스카이·아이스링크·샤롯데씨어터와 한 건물',
      tips: '잠실 일정의 저녁 기본값',
      links: { official: 'https://www.lwt.co.kr' },
      status: 'ok', tags: ['저녁','실내'] },

    { id: 'chinatown_food', name: '인천 차이나타운 짜장면 (공화춘·신승반점)', type: 'food', region: 'incheon', lat: 37.4753, lng: 126.6176,
      oh: ['10:00','21:00'],
      dur: 70, cost: { a: 12000, t: 12000, c: 10000, note: '1인 1~1.3만원' },
      hours: '10:00~21:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '차이나타운 공영주차장',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '짜장면 발상지에서 먹는 짜장면 + 짜장면박물관(유료 1,000원)',
      tips: '인천 원정일 점심. 화덕만두·공갈빵 간식',
      links: { official: 'https://map.naver.com/p/search/인천 차이나타운' },
      status: 'ok', tags: ['점심','원정'] },

    { id: 'ganghwa_food', name: '강화 향토 점심 (젓국갈비·밴댕이·순무김치)', type: 'food', region: 'ganghwa', lat: 37.7470, lng: 126.4860,
      oh: ['11:00','20:00'],
      dur: 70, cost: { a: 18000, t: 18000, c: 15000, note: '1인 1.5~2만원' },
      hours: '11:00~20:00', closed: '가게별',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '가게 주차',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '강화 특산 향토음식 — 아이용은 갈비 메뉴 안전',
      tips: '읍내 강화풍물시장 2층 식당가도 선택지. 조양방직 카페와 묶기',
      links: { official: 'https://map.naver.com/p/search/강화 젓국갈비' },
      status: 'ok', tags: ['점심','원정'] },

    /* ───────── 숙소 (권역 추천 · 5인 1실/커넥팅룸 확인 필수) ───────── */
    { id: 'stay_yongsan', name: '숙소 A · 용산·서울역권 (서울드래곤시티 등)', type: 'stay', region: 'yongsan', lat: 37.5330, lng: 126.9620,
      dur: 0, cost: { a: 0, t: 0, c: 0, note: '1박 20~35만원대 (패밀리룸/레지던스 기준, 검증 필요)' },
      hours: '체크인 15:00 / 아웃 11:00', closed: '—',
      reserve: 'required', reserveNote: '5인 1실 가능 객실(패밀리·레지던스형) 또는 커넥팅룸 + 주차 조건 확인',
      indoor: true, parking: '호텔 주차 (1박 1~2만원 or 무료 여부 확인)',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '★ 1순위 권역. 국립중앙박물관·전쟁기념관 차 10분, 광화문 15분, 여의도 15분, 강화·인천 진출 시 강변북로 진입 용이',
      tips: '서울드래곤시티(4개 호텔 복합, 그랜드 머큐어 레지던스는 취사 가능 5인실 있음)·인근 서울역 비즈니스호텔 커넥팅룸 비교. 4박 한 곳 고정 권장',
      links: { official: 'https://www.seouldragoncity.com', booking: 'https://www.agoda.com/ko-kr/search?city=14690&rooms=1&adults=2&children=3' },
      status: 'verify', verifyNote: '5인 객실·요금·주차 조건 확인', tags: ['숙소','거점'] },

    { id: 'stay_jamsil', name: '숙소 B · 잠실권 (롯데호텔월드·석촌호수 인근)', type: 'stay', region: 'jamsil', lat: 37.5115, lng: 127.1000,
      dur: 0, cost: { a: 0, t: 0, c: 0, note: '1박 25~45만원대 (검증 필요)' },
      hours: '체크인 15:00 / 아웃 11:00', closed: '—',
      reserve: 'required', reserveNote: '패밀리 트윈+엑스트라베드 or 커넥팅룸',
      indoor: true, parking: '호텔 주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '롯데월드·서울스카이·아이스링크·샤롯데 도보. 귀가일 경부고속도로 진입 쉬움',
      tips: '잠실 중심 일정(플랜 B·놀이형)에 적합. 강화·인천 원정에는 불리(서울 횡단 1시간+)',
      links: { official: 'https://www.lottehotel.com/world-hotel', booking: 'https://www.agoda.com/ko-kr/search?city=14690&rooms=1&adults=2&children=3' },
      status: 'verify', verifyNote: '5인 객실·요금 확인', tags: ['숙소'] },

    { id: 'stay_yeouido', name: '숙소 C · 여의도·영등포권 (패밀리 호텔·레지던스)', type: 'stay', region: 'yeouido', lat: 37.5210, lng: 126.9250,
      dur: 0, cost: { a: 0, t: 0, c: 0, note: '1박 15~28만원대 (검증 필요)' },
      hours: '체크인 15:00 / 아웃 11:00', closed: '—',
      reserve: 'required', reserveNote: '5인 객실 필터로 검색 (야놀자·여기어때·아고다)',
      indoor: true, parking: '호텔 주차',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '국회·KBS·더현대 도보권, 올림픽대로로 강화·인천 진출 유리, 가격 상대적으로 합리적',
      tips: '원정 비중 높은 플랜(C·D)에 유리. 광화문·잠실은 차 20~30분',
      links: { booking: 'https://www.agoda.com/ko-kr/search?city=14690&rooms=1&adults=2&children=3' },
      status: 'verify', verifyNote: '5인 객실·요금 확인', tags: ['숙소'] },

    { id: 'stay_hanok', name: '숙소 D · 북촌·서촌 한옥스테이 (1~2박 체험용)', type: 'stay', region: 'gwanghwamun', lat: 37.5820, lng: 126.9830,
      dur: 0, cost: { a: 0, t: 0, c: 0, note: '1박 25~40만원 (독채 5인, 검증 필요)' },
      hours: '체크인 15:00 / 아웃 11:00', closed: '—',
      reserve: 'required', reserveNote: '독채 5인 가능 여부·온돌·주차 확인 (한옥은 주차 없는 곳 많음)',
      indoor: true, parking: '대부분 없음 — 인근 공영주차장 이용',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '경복궁·북촌 도보, 한옥 온돌에서 자는 경험 자체가 여행',
      tips: '4박 전부는 부담 → 마지막 1박만 한옥으로 바꾸는 "체험 옵션". 주차가 최대 변수',
      links: { booking: 'https://www.airbnb.co.kr/s/서울-종로구/homes?adults=2&children=3' },
      status: 'verify', verifyNote: '독채·주차 확인', tags: ['숙소','체험'] },

    /* ───────── 근교 원정 ───────── */
    { id: 'gh_luge', name: '강화 씨사이드리조트 루지 + 곤돌라', type: 'far', region: 'ganghwa', lat: 37.6300, lng: 126.4870,
      oh: ['10:00','17:00'],
      dur: 150, cost: { a: 31000, t: 31000, c: 31000, note: '루지+곤돌라 2회권 31,000 / 1회권 19,000 (어린이 1회 7,000)' },
      hours: '12월 기준 평일 10:00~17:00 / 주말 09:30~17:30', closed: '강풍·결빙 시 중단',
      reserve: 'recommended', reserveNote: '와그·클룩 등 할인권 사전 구매 가능',
      indoor: false, parking: '리조트 대형 무료주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '아시아 최장 1.8km 루지 코스 2개 + 서해 조망 곤돌라',
      tips: '초3은 신장 제한(단독 탑승 기준) 확인 → 보호자 동승 가능. 방한·장갑 필수, 오전 도착이 유리. 2회권이 만족도 대비 합리적',
      links: { official: 'https://www.ganghwa-resort.co.kr' },
      status: 'ok', tags: ['야외','원정','체험'] },

    { id: 'gh_jeondeung', name: '전등사 (강화 삼랑성)', type: 'far', region: 'ganghwa', lat: 37.6318, lng: 126.4855,
      oh: ['08:30','18:00'],
      dur: 70, cost: { a: 4000, t: 3000, c: 1500, note: '성인 4,000 / 청소년 3,000 / 어린이 1,500 (확인)' },
      hours: '08:30~18:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '전등사 주차장(유료)',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '현존 최고(最古) 사찰 중 하나, 성곽 안 절. 루지 리조트 차 5분',
      tips: '루지 후 30~40분 산책 코스로. 겨울 눈 쌓이면 최고',
      links: { official: 'https://www.jeondeungsa.org' },
      status: 'ok', tags: ['야외','원정','역사'] },

    { id: 'gh_peace', name: '강화평화전망대 (북한 조망)', type: 'far', region: 'ganghwa', lat: 37.7853, lng: 126.4470,
      closedDow: ['월'], oh: ['09:00','17:00'],
      dur: 70, cost: { a: 2500, t: 1700, c: 1000, note: '성인 2,500 / 청소년 1,700 / 어린이 1,000 (확인)' },
      hours: '09:00~17:00 (동절기, 입장 16:30 마감)', closed: '월요일 → 여행기간 정상',
      reserve: 'none', reserveNote: '민통선 검문소 통과 — 전원 신분증 지참',
      indoor: 'mixed', parking: '전망대 주차장',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '망원경으로 북한 개풍군 마을이 육안으로 보임 — 대전에서는 절대 불가한 경험',
      tips: '강화 북단 → 루지(남단)와 왕복 1시간. 강화 일정은 "루지→읍내 점심→전망대→서울"로 남→북→동 순서가 효율적',
      links: { official: 'https://www.ganghwa.go.kr/open_content/tour' },
      status: 'ok', tags: ['원정','역사','신분증'] },

    { id: 'gh_joyang', name: '조양방직 (방직공장 개조 카페·미술관)', type: 'far', region: 'ganghwa', lat: 37.7447, lng: 126.4837,
      oh: ['11:00','20:00'],
      dur: 60, cost: { a: 9000, t: 9000, c: 7000, note: '음료 1인 7~9천원' },
      hours: '11:00~20:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '카페 주차장',
      ages: { k1: 3, k2: 2, k3: 2 },
      why: '1930년대 방직공장을 통째로 카페로 — 중2 사진 취향 저격',
      tips: '읍내 점심 후 커피 겸 몸 녹이기. 바로 옆 소창체험관(무료)도 함께',
      links: { official: 'https://map.naver.com/p/search/조양방직' },
      status: 'ok', tags: ['카페','원정','사진'] },

    { id: 'gh_socchang', name: '강화 소창체험관 (무료 손수건 만들기)', type: 'far', region: 'ganghwa', lat: 37.7487, lng: 126.4846,
      closedDow: ['월'], oh: ['10:00','17:00'],
      dur: 50, cost: { a: 0, t: 0, c: 0, note: '무료 (소창 손수건 스탬프 체험 무료)' },
      hours: '10:00~17:00', closed: '월요일 → 여행기간 정상',
      reserve: 'none', reserveNote: '현장 접수',
      indoor: true, parking: '인근 공영',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '강화 직물 역사 + 손수건 스탬프 체험 — 초3 만족도 높은 무료 체험',
      tips: '조양방직 도보 3분. 고려궁지·강화역사박물관도 도보권',
      links: { official: 'https://www.ganghwa.go.kr/open_content/tour' },
      status: 'ok', tags: ['무료','체험','원정'] },

    { id: 'gh_dongmak', name: '동막해변 (서해 일몰·갯벌)', type: 'far', region: 'ganghwa', lat: 37.6098, lng: 126.4340,
      dur: 40, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '상시 · 1월 일몰 17:35 전후', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '해변 공영주차',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '강화 남단 서해 일몰. 루지 리조트 차 15분',
      tips: '평화전망대 대신 "남부 집중" 강화 코스를 짤 때 마무리로. 바람 매우 강함, 20분만',
      links: { official: 'https://map.naver.com/p/search/동막해변' },
      status: 'ok', tags: ['무료','야외','일몰'] },

    { id: 'ic_chinatown', name: '인천 차이나타운 + 송월동 동화마을 + 개항장', type: 'far', region: 'incheon', lat: 37.4753, lng: 126.6176,
      oh: ['10:00','18:00'],
      dur: 120, cost: { a: 1000, t: 1000, c: 1000, note: '거리 무료, 짜장면박물관 1,000원' },
      hours: '10:00~18:00 (박물관), 거리 상시', closed: '박물관 월요일',
      reserve: 'none', reserveNote: '—',
      indoor: 'mixed', parking: '차이나타운 공영주차장',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '삼국지 벽화거리·패루·동화마을 벽화·개항기 근대건축(일본 은행 거리)',
      tips: '점심(짜장면) 포함 2시간. 월미도 차 5분. 초3은 동화마을에서 사진 놀이',
      links: { official: 'https://www.incheon.go.kr/tour' },
      status: 'ok', tags: ['원정','사진'] },

    { id: 'ic_wolmi', name: '월미도 + 월미바다열차', type: 'far', region: 'incheon', lat: 37.4736, lng: 126.5977,
      closedDow: ['월'], oh: ['10:00','18:00'],
      dur: 100, cost: { a: 11000, t: 8000, c: 7000, note: '바다열차 평일 성인 11,000 / 청소년 8,000 / 어린이 7,000 (주말 +3천)' },
      hours: '바다열차 10:00~18:00 내외 (동절기 확인)', closed: '월요일 (바다열차)',
      reserve: 'none', reserveNote: '—',
      indoor: 'mixed', parking: '월미공원 주차',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '국내 최장 도심 관광 모노레일(6.1km) — 서해·항구 조망. 월미테마파크 디스코팡팡은 초6·중2 취향',
      tips: '차이나타운 → 월미도 → 서울 귀환. 바다열차 40분 순환. 겨울 바닷바람 강함',
      links: { official: 'https://www.wolmiseatrain.or.kr' },
      status: 'verify', verifyNote: '동절기 운행 시간표 확인', tags: ['원정','체험'] },

    { id: 'ic_letters', name: '국립세계문자박물관 (송도)', type: 'far', region: 'incheon', lat: 37.3939, lng: 126.6352,
      closedDow: ['월'], oh: ['10:00','18:00'],
      dur: 100, cost: { a: 0, t: 0, c: 0, note: '무료 (기획전 유료 가능)' },
      hours: '10:00~18:00 (입장 17:30 마감)', closed: '월요일 → 여행기간 정상',
      reserve: 'recommended', reserveNote: '어린이체험실은 회차 예약 경쟁 심함 — 오픈일 확인',
      indoor: true, parking: '박물관 주차(유료)',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '2023년 개관, 세계 문자 역사 — 퀄리티 높은 무료 어린이체험실. 국립한글박물관 휴관(2028년까지)의 대안',
      tips: '송도 센트럴파크 바로 옆. 인천 원정일 첫 방문지로(10시 개관 맞춰)',
      links: { official: 'https://www.mow.or.kr' },
      status: 'ok', tags: ['무료','실내','원정'] },

    { id: 'ic_centralpark', name: '송도 센트럴파크', type: 'far', region: 'incheon', lat: 37.3928, lng: 126.6380,
      dur: 50, cost: { a: 0, t: 0, c: 0, note: '무료 (보트는 동절기 휴무 가능)' },
      hours: '상시', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '공원 주차(유료)',
      ages: { k1: 2, k2: 2, k3: 2 },
      why: '해수 수로 공원과 초고층 스카이라인 — 미래도시 풍경',
      tips: '문자박물관 후 30분 산책 + 트라이볼 사진. 겨울 바람 강하니 짧게',
      links: { official: 'https://www.insiseol.or.kr' },
      status: 'ok', tags: ['무료','야외','원정'] },

    { id: 'ic_landing', name: '인천상륙작전기념관', type: 'far', region: 'incheon', lat: 37.4460, lng: 126.6640,
      closedDow: ['월'], oh: ['09:00','18:00'],
      dur: 60, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '09:00~18:00', closed: '월요일 → 여행기간 정상',
      reserve: 'none', reserveNote: '—',
      indoor: 'mixed', parking: '기념관 주차',
      ages: { k1: 3, k2: 2, k3: 1 },
      why: '전쟁기념관 봤다면 스킵 가능. 역사 좋아하는 중2용 선택지',
      tips: '송도↔차이나타운 사이에 있어 경유로 30~40분',
      links: { official: 'https://www.incheon.go.kr/museum' },
      status: 'ok', tags: ['무료','원정','역사'] },

    { id: 'wonderbox', name: '파라다이스시티 원더박스 (영종, 실내 테마파크)', type: 'far', region: 'yeongjong', lat: 37.4470, lng: 126.4530,
      oh: ['10:00','18:00'],
      dur: 180, cost: { a: 25000, t: 25000, c: 25000, note: '자유이용권 2.5만원 내외 (확인)' },
      hours: '주말·시즌 위주 운영 — 평일 운영 여부 필수 확인', closed: '평일 휴무 많음',
      reserve: 'recommended', reserveNote: '운영일 확인 후 온라인 예매',
      indoor: true, parking: '파라다이스시티 주차(무료)',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '실내 서커스 테마 놀이공원 — 한파·강풍 시 인천 원정의 실내 대체안',
      tips: '평일 운영 안 하면 제외. 인천공항 옆이라 서울 복귀 1시간',
      links: { official: 'https://www.p-city.com' },
      status: 'verify', verifyNote: '평일 운영 여부·요금 확인', tags: ['실내','원정'] },

    { id: 'pj_imjingak', name: '임진각 평화누리 + 평화곤돌라 (DMZ)', type: 'far', region: 'paju', lat: 37.8894, lng: 126.7404,
      oh: ['10:00','17:00'],
      dur: 150, cost: { a: 11000, t: 9000, c: 9000, note: '곤돌라 일반캐빈 왕복 성인 1.1만 / 어린이 9천 내외 (크리스탈캐빈 +2~3천, 확인)' },
      hours: '곤돌라 10:00~17:00 내외 (동절기)', closed: '—',
      reserve: 'none', reserveNote: '곤돌라는 현장 구매. DMZ 안보관광(제3땅굴)은 별도 예약',
      indoor: 'mixed', parking: '임진각 대형주차(유료)',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '곤돌라로 민통선 안 캠프 그리브스 진입 — 분단 현장을 눈으로. 대전에서 가장 멀고 가장 특별',
      tips: '전원 신분증. 평화누리 바람의 언덕은 겨울 바람 매우 강함. 헤이리·지혜의숲과 묶어 파주 반일',
      links: { official: 'https://www.dmzgondola.com' },
      status: 'ok', tags: ['원정','역사','신분증'] },

    { id: 'pj_heyri', name: '헤이리 예술마을', type: 'far', region: 'paju', lat: 37.7912, lng: 126.6944,
      oh: ['11:00','18:00'],
      dur: 100, cost: { a: 8000, t: 8000, c: 8000, note: '마을 무료, 박물관·체험관 개별 5천~1.5만원' },
      hours: '11:00~18:00 (시설별)', closed: '월·화 휴무 시설 많음',
      reserve: 'none', reserveNote: '—',
      indoor: 'mixed', parking: '마을 내 주차',
      ages: { k1: 2, k2: 2, k3: 3 },
      why: '건축·소규모 박물관·카페 마을 — 점심 겸 산책',
      tips: '임진각 → 헤이리 점심 → 지혜의숲 → 서울. 초3용 체험 박물관(장난감·트릭아트 등) 선택',
      links: { official: 'https://www.heyri.net' },
      status: 'ok', tags: ['원정','점심'] },

    { id: 'pj_forest', name: '지혜의숲 (파주출판도시)', type: 'far', region: 'paju', lat: 37.7115, lng: 126.6910,
      oh: ['10:00','20:00'],
      dur: 60, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '10:00~20:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '아시아출판문화정보센터 주차(무료)',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '8m 높이 책장 도서관 — 별마당도서관의 원조 격, 무료',
      tips: '파주 원정 마무리, 몸 녹이며 1시간. 서울 복귀 50분',
      links: { official: 'https://www.forestofwisdom.or.kr' },
      status: 'ok', tags: ['무료','실내','원정'] },

    { id: 'gm_cave', name: '광명동굴', type: 'far', region: 'gwacheon', lat: 37.4278, lng: 126.8665,
      closedDow: ['월'], oh: ['09:00','18:00'],
      dur: 120, cost: { a: 6000, t: 3500, c: 2000, note: '성인 6,000 / 청소년 3,500 / 어린이 2,000 (확인)' },
      hours: '09:00~18:00 (입장 17:00 마감)', closed: '월요일 → 여행기간 정상',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '동굴 주차(유료)',
      ages: { k1: 2, k2: 3, k3: 3 },
      why: '폐광을 개조한 미디어아트 동굴 — 동굴 안은 연중 12도라 겨울에 오히려 따뜻함',
      tips: '과천과학관과 묶어 서울 남서부 하루. 동굴 안 습해 미끄럼 주의',
      links: { official: 'https://www.gm.go.kr/cv' },
      status: 'ok', tags: ['저비용','실내','원정'] },

    { id: 'seoul_zoo', name: '서울대공원 동물원 + 스카이리프트', type: 'far', region: 'gwacheon', lat: 37.4270, lng: 127.0165,
      oh: ['09:00','18:00'],
      dur: 180, cost: { a: 5000, t: 3000, c: 2000, note: '동물원 성인 5,000 / 청소년 3,000 / 어린이 2,000. 리프트·코끼리열차 별도' },
      hours: '09:00~18:00 (동절기)', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '대공원 주차(유료)',
      ages: { k1: 1, k2: 2, k3: 3 },
      why: '과천과학관 바로 옆. 초3 취향, 겨울엔 실내관(열대·야행관) 위주',
      tips: '한파엔 비추. 날씨 좋은 날 과학관 후 2시간 옵션',
      links: { official: 'https://grandpark.seoul.go.kr' },
      status: 'ok', tags: ['야외','원정'] },

    /* ───────── 쇼핑·휴식 ───────── */
    { id: 'starfield_lib', name: '별마당도서관 (스타필드 코엑스)', type: 'shop', region: 'jamsil', lat: 37.5101, lng: 127.0603,
      oh: ['10:30','22:00'],
      dur: 40, cost: { a: 0, t: 0, c: 0, note: '무료' },
      hours: '10:30~22:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '코엑스 주차',
      ages: { k1: 3, k2: 2, k3: 2 },
      why: '13m 책장 인증샷 명소, 아쿠아리움과 한 건물',
      tips: '코엑스 아쿠아리움 전후 30분',
      links: { official: 'https://www.starfield.co.kr/coexmall' },
      status: 'ok', tags: ['무료','실내','사진'] },

    { id: 'myeongdong_st', name: '명동 거리 + 남대문시장', type: 'shop', region: 'gwanghwamun', lat: 37.5636, lng: 126.9838,
      dur: 90, cost: { a: 10000, t: 10000, c: 10000, note: '길거리 간식 1인 1만원 내외' },
      hours: '길거리 음식 노점 16:00~22:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: false, parking: '명동 공영주차',
      ages: { k1: 3, k2: 3, k3: 3 },
      why: '길거리 음식 + 캐릭터숍 + 외국인 관광객 분위기. 난타·남산과 도보권',
      tips: '난타 공연 전후 1시간. 남대문시장 호떡·칼국수 골목은 낮',
      links: { official: 'https://map.naver.com/p/search/명동 거리' },
      status: 'ok', tags: ['야외','간식'] },

    { id: 'lwmall', name: '롯데월드몰 (아쿠아리움·시네마·서점)', type: 'shop', region: 'jamsil', lat: 37.5133, lng: 127.1040,
      oh: ['10:30','22:00'],
      dur: 90, cost: { a: 0, t: 0, c: 0, note: '무료 (롯데월드 아쿠아리움 별도 3.5만)' },
      hours: '10:30~22:00', closed: '—',
      reserve: 'none', reserveNote: '—',
      indoor: true, parking: '몰 주차(유료)',
      ages: { k1: 3, k2: 3, k3: 2 },
      why: '서울스카이·아이스링크·샤롯데씨어터 사이 대기 시간 채우기',
      tips: '공연·전망대 시간 사이 "버퍼"로 쓰는 카드',
      links: { official: 'https://www.lwt.co.kr' },
      status: 'ok', tags: ['실내','쇼핑'] }
  ]
};
